// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0kqMDphr5Px4zpM7owcDtX0Ef88--gi8',
    appId: '1:399220080948:web:e8308e0cd97b349a216561',
    messagingSenderId: '399220080948',
    projectId: 'foot-wear-55b9e',
    authDomain: 'foot-wear-55b9e.firebaseapp.com',
    storageBucket: 'foot-wear-55b9e.appspot.com',
    measurementId: 'G-RYMNE38QD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBcQtQZtxEkYuD6_W_b8J3oUMYqIutOM',
    appId: '1:399220080948:android:7cd02fc94f910076216561',
    messagingSenderId: '399220080948',
    projectId: 'foot-wear-55b9e',
    storageBucket: 'foot-wear-55b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA09WdCzkFk2rQZ_gegEd2NGhgcoEkHzHM',
    appId: '1:399220080948:ios:e077829e934082dd216561',
    messagingSenderId: '399220080948',
    projectId: 'foot-wear-55b9e',
    storageBucket: 'foot-wear-55b9e.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA09WdCzkFk2rQZ_gegEd2NGhgcoEkHzHM',
    appId: '1:399220080948:ios:e077829e934082dd216561',
    messagingSenderId: '399220080948',
    projectId: 'foot-wear-55b9e',
    storageBucket: 'foot-wear-55b9e.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0kqMDphr5Px4zpM7owcDtX0Ef88--gi8',
    appId: '1:399220080948:web:4df44ea826fb9b2f216561',
    messagingSenderId: '399220080948',
    projectId: 'foot-wear-55b9e',
    authDomain: 'foot-wear-55b9e.firebaseapp.com',
    storageBucket: 'foot-wear-55b9e.appspot.com',
    measurementId: 'G-89XBL10K4T',
  );
}
